apiVersion: kyverno.io/v2beta1
kind: Policy
metadata:
  name: audit-event-on-delete
spec:
  background: false
  rules:
  - name: generate-event-on-delete-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          operations:
          - DELETE
    generate:
      apiVersion: v1
      kind: Event
      name: "delete.{{ random('[a-z0-9]{12}') }}" # TODO: better name?
      namespace: "$SN_ICR_NAMESPACE"
      data:
        firstTimestamp: "{{ time_now_utc() }}"
        involvedObject:
          apiVersion: v1
          kind: Secret
          name: "{{ request.name }}"
          namespace: "{{ request.namespace }}"
          uid: "{{request.oldObject.metadata.uid}}"
        lastTimestamp: "{{ time_now_utc() }}"
        message: The {{ request.name }} Secret was deleted by {{ request.userInfo | to_string(@) }}.
        reason: Delete
        source:
          component: kyverno
        type: Warning
