apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: enforce-images-use-checksums
spec:
  validationFailureAction: Enforce
  rules:
  - name: checksum
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Only checksums are allowed for container image tags."
      pattern:
        spec:
          containers:
          - image: "*@*"
