apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: verify-image
  annotations:
    policies.kyverno.io/description: >-
      OCI images may be signed to ensure supply chain
      security is maintained. Those signatures can be verified before pulling into
      a cluster. This policy checks the signature of an image repo called
      us.icr.io/sn-labsassets/nginx to ensure it has been signed by verifying
      its signature against the provided public key. This policy serves as an illustration for
      how to configure a similar rule and will require replacing with your image(s) and keys.      
spec:
  validationFailureAction: Enforce
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
          - "us.icr.io/sn-labsassets/nginx:*"
        attestors:
        - entries:
          - keys:
              publicKeys: |
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkkyj1CtCCFyTIU19zPchbQ3NYN71
                tLGyVGJwlzNVPTrjYZlerF1oGcfWzoZDJRN7AGfXbjeCi8VorPWKWjQDpw==
                -----END PUBLIC KEY-----
