apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: verify-image
spec:
  validationFailureAction: Enforce
  rules:
    - name: verify-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
          - "us.icr.io/sn-labsassets/nginx:*"
        attestors:
        - entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkkyj1CtCCFyTIU19zPchbQ3NYN71
                tLGyVGJwlzNVPTrjYZlerF1oGcfWzoZDJRN7AGfXbjeCi8VorPWKWjQDpw==
                -----END PUBLIC KEY-----
